[Network]
send_buffer_max              = 2048    # Max total send buffer size per connection (in bytes)
recv_buffer_max              = 16384   # Max total recv buffer size per connection (in bytes)
recv_buffer_incr             = 4096    # Buffer growth step (in bytes)
header_reserve_hint          = 512     # Initial header allocation hint size
max_header_size              = 8192    # Max total size of all headers
max_header_count             = 64      # Max number of headers allowed
max_body_size                = 8192    # Max size of request body
header_timeout               = 15      # Max time limit for entire header to arrive. After that the connection closes
body_timeout                 = 20      # Max time limit for entire body to arrive. After that the connection closes
idle_timeout                 = 40      # Max time limit for a connection to stay idle. After that the connection closes
max_connections              = 10000   # Max total concurrent connections
max_connections_per_ip       = 10000   # Per-IP connection cap
max_request_burst_per_ip     = 10000   # Initial request tokens per IP
max_requests_per_ip_per_sec  = 10000   # Refill rate (tokens per second per IP)

[Windows]
accept_slots       = 4096    # Number of pre-allocated AcceptEx contexts
connection_threads = "auto"  # IOCP worker thread count
request_threads    = "all"   # Threads executing user handlers

[Linux]
worker_processes = 2      # Max simultaneous worker connections
backlog          = 1024   # Max pending connections in OS listen queue

[Linux.IoUring]
accept_slots     = 64     # Max simultaneous connections being accepted
queue_depth      = 4096   # Internal connection queue depth
batch_size       = 64     # How many connections to process per iteration
file_chunk_size  = 65536  # How big of a file chunk to send at once

[Linux.Epoll]
max_events       = 1024   # How many events should epoll handle at a time

[Misc]
file_cache_size  = 20     # Number of files cached for efficiency